version: "3"
services:
  app:    
    image: brandnewbox/bnb-ruby:2.7-postgresql
    command: bundle exec puma -C config/puma.rb
    env_file: .docker-development-vars
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
  maildev:
    image: djfarrelly/maildev
    ports:
      - "3001:80"
  mongodb:
    image: mongo
    volumes:
      - mongo_data:/data/db
volumes:
  bundle_cache:
  mongo_data:
