version: 2.1
orbs:
  drydock: brandnewbox/drydock@dev:base-image
parameters:
  registry:
    type: string
    default: registry.digitalocean.com
  builder-image:
    type: string
    default: brandnewbox/errbit-builder
  final-image:
    type: string
    default: brandnewbox/errbit
  rancher-context:
    type: string
    default: 'c-tmnrk:p-l87zj'
  rancher-namespace:
    type: string
    default: errbit
  working-directory:
    type: string
    default: /home/bnb/app
workflows:
  devops_flow:
    jobs:
      - drydock/run-danger:
          context: GITHUB
      - drydock/build-and-push:
          name: build-and-push-builder
          built-image: << pipeline.parameters.registry >>/<< pipeline.parameters.builder-image >>:${CIRCLE_SHA1}
          build-target: production-builder
          working-directory: << pipeline.parameters.working-directory >>
          cache-assets: true
          cache-packs: false
          docker-version: default
          build-args: >-
            --build-arg RAILS_MASTER_KEY=${RAILS_PRODUCTION_KEY}
            --build-arg RAILS_ENV=production
          context: DO_BNB_REGISTRY
      - test:
          image: << pipeline.parameters.registry >>/<< pipeline.parameters.builder-image >>:${CIRCLE_SHA1}
          context: DO_BNB_REGISTRY
          requires:
            - build-and-push-builder
      - drydock/build-and-push:
          name: build-and-push-production
          built-image: << pipeline.parameters.registry >>/<< pipeline.parameters.final-image >>:${CIRCLE_SHA1}
          build-target: production
          working-directory: << pipeline.parameters.working-directory >>
          cache-assets: true
          cache-packs: false
          docker-version: default
          build-args: >-
            --build-arg RAILS_MASTER_KEY=${RAILS_PRODUCTION_KEY}
            --build-arg RAILS_ENV=production
          context: DO_BNB_REGISTRY
          filters:
            branches:
              only: /^(main)$/
          requires:
            - build-and-push-builder
      - drydock/create-deployment:
          name: puma-deployment
          rancher-deployment: errbit-deployment
          rancher-container: errbit-container
          rancher-namespace: << pipeline.parameters.rancher-namespace >>
          rancher-context: << pipeline.parameters.rancher-context >>
          image: << pipeline.parameters.registry >>/<< pipeline.parameters.final-image >>:${CIRCLE_SHA1}
          context: DO_BNB_REGISTRY
          filters:
            branches:
              only: /^(main)$/
          requires:
            - build-and-push-production
            - test
jobs:
  test:
    parameters:
      image:
        description: The image to test
        type: string
    docker:
      - image: << parameters.image >>
        auth:
          username: $PRIVATE_REGISTRY_USERNAME
          password: $PRIVATE_REGISTRY_PASSWORD
        environment:
          RAILS_ENV: test
          MONGO_URL: mongodb://localhost:27017/my_database
      - image: circleci/mongo:4
    working_directory: << pipeline.parameters.working-directory >>
    steps:
      - drydock/default-test-steps
